package com.revature.foundations.utils.exceptions;


public class DataSourceException extends RuntimeException {

    public DataSourceException(String message, Throwable cause) {
        super(message, cause);
    }

}